### ISSUE TITLE
[Question] @ Mention support

### ISSUE THREAD

**Issue by sonicer105** [Noiiko/BirthdayBot#2]
Is it possible to make the birthday bot pinging the user when it's their birthday instead of just saying their username and number?

**Comment by Noiiko** [comment]
Yes, it's already capable of doing so but does not do it by default. It can be enabled by issuing the command `bb.config ping on`.

**Comment by bopoh13** [comment]
@NoiTheCat
The setting didn't disable ping. The bot does something 3 times in a row: 1 time in 1-3 hours.
